### ISSUE TITLE
Health rendering dramatically lowers framerate.

### ISSUE THREAD

**Issue by Vallith** [AllTheMods/All-the-mods-7-Sky#220] opened 2022-09-26 02:18 UTC
![image](https://user-images.githubusercontent.com/31032203/192180863-18cd53f4-ca0c-40f5-bc26-9ba3d3317c73.png)

Something to do with either Vibranium armour means when taking damage you get this strange extra layer of hearts.

![image](https://user-images.githubusercontent.com/31032203/192180939-7f1e7ebb-a872-4e77-bf43-a695f2df7ad3.png)

I suspect these layer infinitely for some reason, dragging the FPS down *significantly*.  I'm afraid I don't know much more, but when wearing Vibranium armour and taking damage these extra hearts appear. They seem to keep stacking. I can't find a way currently to get rid of them, so my FPS is permanently significantly lower than what it was. Initially re-connecting to the server removed them, but that has stopped working.

**Comment by Mitchell5200** [comment] 2022-11-04 14:26
Normal Vibranium armour should not be giving a health boost. if you're still having this issue, i need more details about the armour and any other items you have equipped

**Comment by oly2o6** [comment] 2022-11-18 03:42
Closing issue as I was unable to reproduce the hearts or any lag from wearing vibranium armor in my test instance, will be happy to see this reopened if more information can be given in the future

**Closed by oly2o6** 2022-11-18 03:42 UTC
Labels: bug, question
