### ISSUE TITLE
Oak saplings replaced with otherworldly saplings

### ISSUE THREAD

**Issue by benbarker07** [AllTheMods/All-the-mods-7-Sky#88] opened 2022-08-21 08:44 UTC
In the latest version (1.0.2) oak saplings are replaced with otherworldly saplings, meaning silk worms cannot be obtained and infested oak leaves don't drop string.

**Comment by Mitchell5200** [comment] 2022-08-21 08:51
This an issue for ATM7 sky, and i believe it may be caused by occultism

**Comment by enigmaquip** [comment] 2022-08-21 14:25
In my testing, while the name shows `Unstable Otherworld Sapling` it is still a regular oak sapling and grew up as a normal oak tree and was dropping worms fine with the crook. Are you sure this is anything more than a name overwrite? Which I can and will fix

**Comment by benbarker07** [comment] 2022-08-22 13:10
Hmm weird, for me I harvested over 70+ trees and crooked their leaves and got no worms, when I cheated in a silkworm to test it infested all the leaves but when broken with a crook they dropped nothing. I don't know if my instance was a one off but I did continue to test with a few more worms and the same result

**Comment by clarketronics** [comment] 2022-08-22 16:18
Works fine for me, new world created on version 1.0.2

**Comment by benbarker07** [comment] 2022-08-22 23:57
I created my world on 1.0.1 maybe there was an overwrite issue that caused mine to not work?

**Comment by enigmaquip** [comment] 2022-08-23 01:17
It may have been related to the Nihilo bug we're trying to track down where all those recipes stop working.... On Occultism's side this has been fixed in v1.0.3.... if you see issues still please reopen

**Closed by enigmaquip** 2022-08-23 01:17 UTC
