### ISSUE TITLE
uraninite seed can't be used in garden cloche or phytogenic insolator

### ISSUE THREAD

**Issue by Schrimpes** [AllTheMods/All-the-mods-7-Sky#145] opened 2022-09-04 23:26 UTC
the uraninite seed is the only one besides amethyst seed that cannot be used in a garden cloche or the phytogenic insulator

**Comment by enigmaquip** [comment] 2022-09-07 03:34
Duplicate of #103, please check before posting, thanks

**Closed by enigmaquip** 2022-09-07 03:34 UTC
