### ISSUE TITLE
ATM Star from Star Shards Recipe Missing

### ISSUE THREAD

**Issue by DizzyDJW** [AllTheMods/All-the-mods-7-Sky#174] opened 2022-09-17 02:39 UTC
The recipe for the ATM Star made from Star Shards obtained from the Starry Bee is missing entirely.

This completely removes the point of having the Starry Bee at all, and breaks the endgame altogether, as nobody wants to spend literal weeks of irl time accumulating the resources to craft all the ATM Stars needed to craft all of the Creative Items.

Version: 1.0.6

**Comment by RyanP1991** [comment] 2022-09-29 21:13
The Starry Bee is unobtainable anyway, due to no oceans existing in the world so can't get the previous bee

**Comment by Mitchell5200** [comment] 2022-09-30 03:41
The patrick bee does already have a Spirit "soul transmutation" to create the bee

**Comment by DizzyDJW** [comment] 2022-09-30 08:27
> The patrick bee does already have a Spirit "soul transmutation" to create the bee

Then unfortunately it fails to show up in JEI. Only thing shown is fishing it up in Warm Oceans, the ones that don't exist

**Comment by Mitchell5200** [comment] 2022-11-04 10:01
Confirmed working in 1.1.4, Closing

**Closed by Mitchell5200** 2022-11-04 10:01 UTC
