### ISSUE TITLE
mod Ex Machinis Flux sieve

### ISSUE THREAD

**Issue by Willian7777** [AllTheMods/All-the-mods-7-Sky#201] opened 2022-09-22 04:15 UTC
Flux sieve I was playing and I noticed a somewhat unusual behavior in the operation of the machine.
When we inserted a stack of 64 items in the auto Flux sieve did not generate items, but on other occasions it generated a stack of 64 items of only one of the items that are possible to drop from the inserted block to perform the processing, I performed the test with the three upgredes available: gold, diamond and netherite and occurred with all three.
I also tested it with no upgrade and it worked correctly, is it some buff from the upgrade cards or is it a bug?

![mesh](https://user-images.githubusercontent.com/114128407/191657148-3cb9bc1f-c015-41ff-9e5c-3f04878bf58a.png)
![chestflux](https://user-images.githubusercontent.com/114128407/191657157-9804689c-d63d-401c-9e0e-301d21c7ec03.png)
![fluxSieve](https://user-images.githubusercontent.com/114128407/191657159-b8760d6f-b08c-4ae6-b747-01b3f3a36f02.png)
![flux](https://user-images.githubusercontent.com/114128407/191657161-d5efddf7-d48b-467b-9aca-0bf64dd1b683.png)

**Comment by Mitchell5200** [comment] 2022-09-22 04:19
This is an ATM7 TTS issue, Transferring

**Comment by jeremiahwinsley** [comment] 2022-09-22 06:08
This is not a bug - result is rolled per stack and multiplied by the stack size, not rolled per item. This doesn't make anything more or less rare, the chances are still the same averaged over hundreds of rolls.

**Closed** 2022-11-04 14:02 UTC
