### ISSUE TITLE
Island deleting itself

### ISSUE THREAD

**Issue by RyanP1991** [AllTheMods/All-the-mods-7-Sky#95] opened 2022-08-22 18:06 UTC
If you click on the East Mode quest which is located on the far left side on the Getting Started chapter for some reason it deletes the island

**Comment by Mitchell5200** [comment] 2022-11-04 07:21
Unable to Locate Quest in 1.1.4, and therefore unable to reproduce, Closing

**Closed by Mitchell5200** 2022-11-04 07:21 UTC
