### ISSUE TITLE
Crashes when opening integrated dynamics terminal

### ISSUE THREAD

**Issue by tbsorb** [AllTheMods/All-the-mods-7-Sky#288] opened 2022-10-13 23:53 UTC
Just updated to 1.1.1 Started a new world and once I got to the point of use intdyn, i crafted a terminal and set it on the logic cable. Now everytime I click the terminal, the server crashes. Error log attached. Tried breaking it and putting it back. Tried deleting it and grabbing a new one via OP. Still no dice.
[latest.log](https://github.com/AllTheMods/All-the-mods-7-Sky/files/9781325/latest.log)

**Comment by tbsorb** [comment] 2022-10-14 01:55
Just adding to this. Reinstalled server, made a new world and it had the same behavior. Used JEI to grab portable terminal out and try with that. Also same behavior.

**Comment by tbsorb** [comment] 2022-10-14 01:56
[crash-2022-10-14_01.54.32-server.txt](https://github.com/AllTheMods/All-the-mods-7-Sky/files/9781820/crash-2022-10-14_01.54.32-server.txt)

**Comment by LegitLunatic** [comment] 2022-10-15 05:12
I'm having the exact same issue, however for me it only happens on a server, with singleplayer working fine.

**Comment by Aydan-xd** [comment] 2022-10-17 02:23
the same thing is happening to me every time I open the storage terminal the server I'm on crashes

**Comment by jaarenhoevel** [comment] 2022-10-19 11:07
Looks like it has been fixed by the author of Integrated Dynamics. We just have to wait until it makes it's way to a release... 

https://github.com/CyclopsMC/IntegratedTerminals/issues/92

**Comment by zediious** [comment] 2022-10-21 09:02
Unfortunately was missed in the most recent update https://www.curseforge.com/minecraft/modpacks/all-the-mods-7-to-the-sky/files/4036230

Strange as the base ATM 7 got the updated mod recently.

**Comment by Mitchell5200** [comment] 2022-11-04 17:12
Confirmed working on 1.1.4, closing

**Closed as completed by Mitchell5200** 2022-11-04 17:12 UTC
