### ISSUE TITLE
Comforts sleeping bag recipe

### ISSUE THREAD

**Issue by Svennixx** [AllTheMods/All-the-mods-7-Sky#286] opened 2022-10-13 17:41 UTC
The newly added mod comforts has a clashing recipe with "Absent by design". The sleeping bag cannot be made.
![image](https://user-images.githubusercontent.com/5203461/195667668-be8b7871-6793-42f3-aeee-f626b1f57d71.png)
![image](https://user-images.githubusercontent.com/5203461/195667765-bcae15c1-b7b4-4ff5-8080-f909cc4a3195.png)

**Comment by RedStoneGamed** [comment] 2022-10-13 18:57
In all the mods 7 and 8 the button that looks like a loop if you press or hover over it it should let you choose. It worked before…

**Comment by Schrimpes** [comment] 2022-10-13 22:43
there is no such button in this pack, not in the crafting table, in the crafting station, the ae2 grid or backpack crafting

**Comment by Yslohr** [comment] 2022-10-14 05:07
I can vouch for this, the issue is happening regardless of what you try to use to craft it. I have tested for this using the ME Crafting Terminal, a Crafting Station from Tinkers, a Crafting Table and none of those work. I don't think the craft to get it through create works either. My Solution would be to make it out of 6 wool slabs of whatever colour you want to craft it in so that both can be present in the pack.

**Comment by Svennixx** [comment] 2022-10-14 07:29
> In all the mods 7 and 8 the button that looks like a loop if you press or hover over it it should let you choose. It worked before…

Sadly this pack doesn't have that.

**Comment by Mitchell5200** [comment] 2022-11-04 17:11
Fixed and changed, and Confirmed working on 1.1.4, closing

**Closed as completed by Mitchell5200** 2022-11-04 17:11 UTC
